### ISSUE TITLE
C3P0 0.9.5 release not closing connections

### ISSUE THREAD

**Issue by mwienk** [davidmoten/rxjava-jdbc#13]
Hey,

In your documentation, you say you should use a newer version than the pre-8 release of c3p0. But in the latest (0.9.5, which is after pre8), connections don't seem to be closed when done. My connection pool grows with each query, making it unusable.

I would really like to use pooled connections. Is there any (quick) fix?

**Comment by davidmoten** [comment]
I'm assuming the quickest fix would be to use the version in the library
deps now even if is pre-8 but that's obviously not ideal. Have you raised
the issue with c3p0 or do you think there might be a problem with
rxjava-jdbc? Can you debug it a big?

**Comment by bric3** [comment]
Why using a bogus pool anyway. tomcat-jdbc or hikari are more modern, and probably more correct as connection pools

**Comment by davidmoten** [comment]
Thanks Brice, I'll look at that. I should probably make the connection pool
choice up to the user and default to one of the ones you mention if they
are considered more robust.

**Comment by davidmoten** [comment]
I've released 0.5 using Hikari connection pool. Thanks for the suggestion @bric3  and hope this helps @mwienk.

**Comment by bric3** [comment]
wow that was fast ;)

**Comment by bric3** [comment]
> I should probably make the connection pool choice up to the user and default to one of the ones you mention if they are considered more robust.

That would be great, as datasouces can come from the container. In tomcat for exemple it is availble from JNDI.

**Comment by hansgru** [comment]
+1 for JNDI, because c3po is not quite the best solution:
http://www.tomcatexpert.com/blog/2010/03/22/understanding-jdbc-pool-performance-improvements

**Comment by davidmoten** [comment]
I've added brief notes to the README about creating and using a custom ```ConnectionProvider``` (not a new class, was available pre 0.5). This provides the flexibility to plugin whatever connection pooling arrangement you want for example a JNDI datasource.

**Comment by bric3** [comment]
cool, missed that

**Comment by davidmoten** [comment]
I missed it myself, apologies to @mwienk for not making the suggestion to him when he needed it (holidays got in the way).
