### ISSUE TITLE
Take operator combined with single result prevents the connection from being closed

### ISSUE THREAD

**Issue by pawelkrupinski** [davidmoten/rxjava-jdbc#14]
I noticed a connection leak in our code using rxjava-jdbc. This is how to reproduce it:

        Observable<Long> count =
                database.select("select count(*) from x")
                        .getAs(Long.class)
           
        CountDownLatch latch = new CountDownLatch(1);
        count.take(1).subscribe(element -> {
            latch.countDown();
        });

The connection used by the query is not closed.
If you change it to take(2), the connection is closed.
I narrowed it down to the fact that OperatorTake overrides the setProducer method limiting the number of requested items.

Using rxjava 1.0.8 and rxjava-jdbc 0.5.1.

**Comment by davidmoten** [comment]
Thanks, I'll have a look!

**Comment by davidmoten** [comment]
Thanks very much @pawelkrupinski for the succint test case. Should be sorted now and release 0.5.3 will be out soon with a couple of other fixes that I noticed along the way.

**Comment by davidmoten** [comment]
0.5.3 has been released to Maven Central
