### ISSUE TITLE
Test Smell: the wrong parameter order in ''assertEquals'' assertion

### ISSUE THREAD

**Issue by TestSmell** [davidmoten/rxjava-jdbc#147]
Hi!

Description:
we detect that some assertions in your test code have the wrong parameter orders.
For example, the test case named ''testMapObjectExistingClob()'' in ''UtilTest.java'' writes the ''assertEquals'' assertion as 
![image](https://user-images.githubusercontent.com/110402847/184607556-667b6497-e150-4501-b00a-9771f3b64560.png)
However, referring to the API documentation of ''org.junit.Assert. assertEquals'' is ''assertEquals(Object expected, Object actual)''.

Negative:
Using ''assertEquals()'' with the wrong parameter order is a bad test practice.
Because once the test case fails, the ''assertEquals()'' assertion with the wrong parameter order will give the wrong log information.
The log information will say:’’ java.lang.AssertionError: expected [actual value] but found [ excepted value]’’, where it should have said "java.lang.AssertionError: expected [excepted value] but found [actual value]''.
This is confusing, to say the least, and you shouldn't have to deal with a possible misdirection of that message.

Solution:
Generally, the excepted value should be a known value, such as a real number, a string, etc.
The actual value should be the result of the method-under-test.
The best way to eliminate the test smell is to exchange the parameter in ''assertEquals'' assertions.

We list other test cases with the same problem as follows:
1. testMapObjectExistingClob() in UtilTest.java
2. testMapObjectNullClob() in UtilTest.java

**Comment by davidmoten** [comment]
Thanks. I assume this is some automated system raising this issue? If so please fix the final part of the message. 

This part is incorrect because it relists the first problem found: "We list **other** test cases with the same problem as follows". It should say "We list **the** test cases with the same problem as follows"

**Comment by TestSmell** [comment]
hahahahha  :-)

**Comment by davidmoten** [comment]
Weird!
