### ISSUE TITLE
To how get Last inserted Id from MySQL?

### ISSUE THREAD

**Issue by gencube** [davidmoten/rxjava-jdbc#18]
**How do I get last insert id from mysql?**
```java
database.update("insert into person(name,sex,age,dob) values(?,?,?,?)")
.parameters(person.getName(), person.isMale(), person.getAge(), person.getDob());
```
**I prefer to use the NonBlocking Reactive Pattern.**

In JDBC I could so something like this:
```java
Statement stmt = db.prepareStatement(query, Statement.RETURN_GENERATED_KEYS);
stmt.executeUpdate();

ResultSet rs = stmt.getGeneratedKeys();
if (rs.next()){
    result=rs.getInt(1);
}
```
I have also posted this issue in Stackoverflow. It is a common features used in JDBC programming.
http://stackoverflow.com/questions/30610393/rxjava-jdbc-0-5-7-how-to-obtain-last-insert-id

**Comment by gencube** [comment]
BTW, I like what I saw the code sample rxjava here.

**Comment by davidmoten** [comment]
Interesting. I haven't used that feature. So are you imagining something like below?

```java
Observable<Integer> keys = database.updateReturnGeneratedKeys("insert into person(name,sex,age,dob) values(?,?,?,?)")
.keyType(Integer.class)
.parameters(person.getName(), person.isMale(), person.getAge(), person.getDob());
```

**Comment by gencube** [comment]
Sure!! Or to avoid lesser impact to other code already done.
```java
Observable<Integer> keys = database.update("insert into person(name,sex,age,dob) values(?,?,?,?)")
.returnGeneratedKeys(Integer.class)  //  something like this??
.parameters(person.getName(), person.isMale(), person.getAge(), person.getDob());
```

**Comment by davidmoten** [comment]
I'll have a look at this soonish. It's an important feature I think.

**Comment by gencube** [comment]
Yes. It is. It allow the Client side JS code to track the object and use it for updates/delete/paging. 
Even when it is not sent to client side, an internal maps of cache custome coder generated id to actual database id is needed.

**Comment by gencube** [comment]
Form the other PHP realm, you can see that how most web developer will need to deal with
the database interactions. Its a basic SUBSET of this phpmyadmin features and also joomla:
http://demo.phpmyadmin.net/master-config/#PMAURL-2:sql.php?db=sakila&table=actor&server=2&target=&token=b914f12cddc43ec880505d26b91637f9

**Comment by gencube** [comment]
Joomla Controller, similar to JaxRs controller and Spring Controller:
https://github.com/joomla/joomla-cms/blob/staging/components/com_content/controller.php
also, Models:
https://github.com/joomla/joomla-cms/blob/staging/components/com_content/models/articles.php

**Comment by gencube** [comment]
Example:
```php
		$query->select(
			$this->getState(
				'list.select',
				'a.id, a.title, a.alias, a.introtext, a.fulltext, ' .
					'a.checked_out, a.checked_out_time, ' .
					'a.catid, a.created, a.created_by, a.created_by_alias, ' .
					// Use created if modified is 0
					'CASE WHEN a.modified = ' . $db->quote($db->getNullDate()) . ' THEN a.created ELSE a.modified END as modified, ' .
					'a.modified_by, uam.name as modified_by_name,' .
					// Use created if publish_up is 0
					'CASE WHEN a.publish_up = ' . $db->quote($db->getNullDate()) . ' THEN a.created ELSE a.publish_up END as publish_up,' .
					'a.publish_down, a.images, a.urls, a.attribs, a.metadata, a.metakey, a.metadesc, a.access, ' .
					'a.hits, a.xreference, a.featured, a.language, ' . ' ' . $query->length('a.fulltext') . ' AS readmore'
			)
		);
```

**Comment by gencube** [comment]
From my own reading, joomla seems to have the BETTER MVC code pattern layout and also Fluent SQL which the Java Developer like myself does not really fully understand.

Eg: Router, THEY have it for a GOOD reason for routing requests:

https://github.com/joomla/joomla-cms/blob/staging/components/com_content/router.php

**Comment by gencube** [comment]
They bypassed many COMMON C++/C#/java coding pattern with 'forgiving runtime state' coding which avoided a lot of EXCEPTION like nullpointer(with defaults value) and also plenty of static methods which runs really fast. Which is why its popular now in the younger generation of coder.

**Comment by gencube** [comment]
How most if not all PHP talks to mysql:
http://php.net/manual/en/book.mysqli.php

**Comment by gencube** [comment]
Missing EVEN from the typical JDBC:
```php
mysqli::$affected_rows — Gets the number of affected rows in a previous MySQL operation
mysqli::$insert_id — Returns the auto generated id used in the last query
mysqli::ping — Pings a server connection, or tries to reconnect if the connection has gone down
mysqli::$thread_id — Returns the thread ID for the current connection
... others...
```
They seems to have perfected it.

**Comment by gencube** [comment]
Another example Fetching arrays, clean code with no exception handling in code:
http://php.net/manual/en/mysqli-result.fetch-array.php

**Comment by gencube** [comment]
I actually prefers the Criteria Pattern from Hibernate over the RAW SQL SYNTAX of mysqli. But the mysqli pattern is better than JDBC itself. That is why I suggest if you like to work with ORMlite.

**Comment by davidmoten** [comment]
>Another example Fetching arrays, clean code with no exception handling in code:
http://php.net/manual/en/mysqli-result.fetch-array.php

So they maybe don't have checked exceptions but you have to handle exceptions somewhere.

**Comment by davidmoten** [comment]
@gencube I've added returning generated keys documented [here](https://github.com/davidmoten/rxjava-jdbc#returning-generated-keys). Can you try it out using version [0.6.0-RC1](https://github.com/davidmoten/rxjava-jdbc/releases/tag/0.6.0-RC1)

**Comment by gencube** [comment]
Hi David, Thanks mate. Will try.
