### ISSUE TITLE
How to specify a schema to be used

### ISSUE THREAD

**Issue by KevinSjoberg** [davidmoten/rxjava-jdbc#21]
Hi.

Is there a way to specify what schema to be used when executing statements? As of 9.4 you can specify [currentSchema](https://jdbc.postgresql.org/documentation/94/connect.html#connection-parameters) as a connection parameter but unfortunately I can't use that for my use case.

I'm sorry if this issue is in the wrong place, but I was unsure where to put it.

**Comment by sparty02** [comment]
@KevinSjoberg Have you tried prefixing your table names with the schema in your SQL?  i.e.:
```sql
select * from schema.person
```
This introduces some maintenance headaches (i.e. what if you change your schema name, or use multi-tenant schemas), but it depends on your use case.

**Comment by KevinSjoberg** [comment]
@sparty02 that is good enough, but I need to insert the schema dynamically. I tried to do the following without luck.

```
database.select("SELECT column FROM ?.settings").parameter(schemaVariable).getAs(String.class)
```

but it did not substitute the question mark with the contents of `schemaVariable`.

**Comment by sparty02** [comment]
Ah, that's a JDBC thing.  You can't parameterize table names in ```PreparedStatement```s

**Comment by sparty02** [comment]
So.... options may be:
* Set the ```currentSchema``` property via the connection you obtain (you mentioned you couldn't do this, but not sure why).
* Dynamically create the table name before passing to the select method.  If you do this, be careful in regards to SQL injection vulnerabilities!

**Comment by KevinSjoberg** [comment]
@sparty02 the reason I cant use currentSchema in my connection string is that we're using PgBouncer as a middleman and it does not support it.

I guess I could just go with `String.format` and substitute `%s` for the schema before executing the statement. The schema name are grabbed internally, so it could never come from a user, hence, SQL injection should not be a problem.

**Comment by sparty02** [comment]
@KevinSjoberg Gotcha...   I agree then, ```String.format``` is probably your best bet then.

**Comment by davidmoten** [comment]
Thanks guys, I agree `String.format` seems the way to go.

**Comment by KevinSjoberg** [comment]
Alright, thanks for helping out! I'm closing this one.
