### ISSUE TITLE
Perhaps consider doing a join development with Ormlite into RxOrmLite.

### ISSUE THREAD

**Issue by gencube** [davidmoten/rxjava-jdbc#22]
http://ormlite.com/easy_java_orm.shtml
Author had done support on such syntax
 Supports MySQL, Postgres, Microsoft SQL Server, H2, Derby, HSQLDB, and Sqlite and can be extended to additional databases relatively easily.
Provisional support for DB2, Oracle, ODBC, and Netezza. Contact the author if your database type is not supported.

**Comment by gencube** [comment]
Lightweight and annotation driven compared to Hibernate monster library. BUT, please use JPA annotation to map the model object, it will reduces the code changes for user to switch from another framework like hibernate or JPA.

**Comment by gencube** [comment]
Another possibility is to map JPA to the NoSQL paradigm, like what Guy Kawasaki said about leaping the next curve.
http://www.infoq.com/research/nosql-databases

**Comment by davidmoten** [comment]
I'm not reallly interested in creating an ORM product.  Some minor convenience stuff sure and there might be a little overlap.

**Comment by gencube** [comment]
Ok. I think I can see where you are heading...

How about consider at least implementing something like this for rx-jdbc?

http://www.mkyong.com/hibernate/hibernate-criteria-examples/
**2. Criteria example**
```java
   public static List getStockDailyRecordCriteria(Date startDate,Date endDate,
        Long volume,Session session){
 
	Criteria criteria = session.createCriteria(StockDailyRecord.class);
	if(startDate!=null){
		criteria.add(Expression.ge("date",startDate));
	}
	if(endDate!=null){
		criteria.add(Expression.le("date",endDate));
	}
	if(volume!=null){
		criteria.add(Expression.ge("volume",volume));
	}
	criteria.addOrder(Order.asc("date"));
 
	return criteria.list();
  }
```

**Comment by gencube** [comment]
This can help user of your library to support multiple type of jdbc database syntax and also avoid syntax typo error.
