### ISSUE TITLE
Named parameters

### ISSUE THREAD

**Issue by davidmoten** [davidmoten/rxjava-jdbc#24]
For simple queries jdbc parameters using ? are fine but more complex queries would benefit from named parameters (`:name` for instance).

This is quite doable, just needs good integration with the API. 

Was thinking 

`db.named()` gives builders that always use named parameters in sql and runtime checks on the sql format would occur.

**Comment by gencube** [comment]
AH...

**Comment by sparty02** [comment]
Could also consider sibling methods to the existing ```parameter``` and ```parameters``` methods.  Just thinking out loud....

Something like:
```java
namedParameter(key, value)  // 1 to many
namedParameters(Map<K,V> parameterMap)
```

*e.g.*

Existing example using ordered parameters:
```java
db.select("select name from person where name > ?  and score < ? order by name")
    .parameter("BARRY")
    .parameters(Observable.from(100))
```
....with named parameters (not exactly sure how Observable parameters affect this yet)
```java
db.select("select name from person where name > :name  and score < :score order by name")
    .namedParameter("name", "BARRY")
    .namedParameter("score", Observable.from(100))
```
...or
```java
Map<String, ?> paramMap = new HashMap<>();
paramMap.put("name", "BARRY");
paramMap.put("score", Observable.from(100));

db.select("select name from person where name > :name  and score < :score order by name")
    .namedParameters(paramMap)
```
...or maybe even
```java
Map<String, ?> paramMap = new HashMap<>();
paramMap.put("name", "BARRY");
paramMap.put("score", Observable.from(100));

db.select("select name from person where name > :name  and score < :score order by name")
    .parameterMap(paramMap)
```

**Comment by davidmoten** [comment]
Thanks @sparty02, I was thinking of something similar too. One option that would reduce the noise (`namedParameter`) is to add an overload `parameter(key,value)` and do the right thing if `Map<String,?>` was passed to the `parameters` method either in an Observable or straight.

```java
db.select("select name from person where name > :name  and score < :score order by name")
    .parameter("name", "BARRY")
    .parameter("score", 100);

db.select("select name from person where name > :name  and score < :score order by name")
    .parameters(Observable.just(map1, map2, map3));

db.select("select name from person where name > :name  and score < :score order by name")
    .parameters(map1);
```

If someone called `parameter` with a  single argument or `parameters` with an Observable not of type `Map` and the sql contains names then an error would be thrown. 

This is an interesting usage you mention and I'll have to ponder it:
```java
.parameter("score", Observable.from(100))
```
My first reaction is to shy away from it because we are opened up to the possibility that two parameters are set with Observables of different lengths.

**Comment by gencube** [comment]
```java
db.select("select name from person where name > :name  and score < :score order by name")
    .parameters(Observable.just(map1, map2, map3));   <<< I like this.
```

**Because the front end JQuery/Javascript can call the server with JSON and since we can use 
Jackson ObjectMapper to convert DTO/DAO into Map<String, Object> or Map<String,String>.
The lesser object convertion code the better for speed and heap memory usage.

http://wiki.fasterxml.com/JacksonInFiveMinutes
```java
Map<String,Object> userData = mapper.readValue(new File("user.json"), Map.class);
```

**Comment by gencube** [comment]
The whole idea about ORM Library is about Object to Serial to SQL...the shorter the conversion path from RESTful to Internal JDBC the better.

**Comment by davidmoten** [comment]
I'll build 0.6.1 including named parameters tonight.

**Comment by davidmoten** [comment]
0.6.1 released with named parameters support

**Comment by gencube** [comment]
:dancer:
