### ISSUE TITLE
Question: Interop with JTA?

### ISSUE THREAD

**Issue by sparty02** [davidmoten/rxjava-jdbc#29]
Does rxjava-jdbc's transaction support interop with JTA?  In other words, will it transparently participate in existing JTA initiated transactions?  Still trying to wrap my head around the 'push' model of observables and not sure if this is possible when inverting the control over to observable streams.

In the use case I'm thinking of, I wouldn't (can't) explicitly commit/rollback/etc *in JDBC*, but rather let the  higher level transaction manager do it on my behalf (whether that be through a UserTransaction API or via declarative transaction demarcation).

Hopefully that makes sense!

**Comment by davidmoten** [comment]
I haven't considered JTA in the writing of rxjava-jdbc and haven't used JTA myself. In short I suppose we don't support JTA yet but you might be able to dummy something up by wrapping the connection with a delegator that controlled commits and rollbacks and notified the JTA manager appropriately and pass that delegating connection to the rxjava-jdbc `Database` to work with.

**Comment by sparty02** [comment]
Makes sense, thanks for the info!  If I take a stab at something that works out, I'll let you know!
