### ISSUE TITLE
ConnectionProviderFromDataSource cleanup connection resources

### ISSUE THREAD

**Issue by Alffrredo** [davidmoten/rxjava-jdbc#32]
ConnectionProviderFromDataSource doesn't release connection resources.

 public void close() {
        // do nothing
}
we should call get() connection and close it manually currently.

**Comment by davidmoten** [comment]
`DataSource` does not offer a `close()` method and is usually  a container managed connection pool and as such closing the data source (the connection pool) is left to the container itself.

Any connection obtained from the `DataSource` in rxjava-jdbc streams is closed by completion, error or unsubscription. It's one of the beauties of the RxJava approach that the client does not have to close connections, statements, ResultSets etc.
