### ISSUE TITLE
Lift with parameterListOperator swallows errors ?

### ISSUE THREAD

**Issue by Crystark** [davidmoten/rxjava-jdbc#42]
Hi,

Consider the following code:
```java
obs
	.map(t -> getParam3(t)
		.flatMap(p3 -> Observable.<Object> just(t.param1, t.param2, p3))
	)
	.lift(db
		.update(query)
		.parameterListOperator()
	)
	.onErrorResumeNext((t) -> {
		L.warn("Something went wrong.", t);
		return Observable.empty();
	});
```

If `getParam3` returns an observable containing an error, I'll never see it unless i put some error handling directly on that observable. I suppose `parameterListOperator ` swallows the error.

I hope you can fix this.
Thanks !

**Comment by davidmoten** [comment]
Thanks for the report. I'll have a look.

**Comment by davidmoten** [comment]
Please retry with 0.6.7.

**Comment by Crystark** [comment]
I didn't keep my test case but i tried reproducing this based on what i wrote up there and i'm still getting no exception shown. The behavior looks a lot like #37.

**Comment by davidmoten** [comment]
I wrote the test at bottom to duplicate and found no problem in the library. 

Your code is 
```java
 .lift(db
        .update(query)
        .parameterListOperator()
    )
```
You need to remember at this point that you get `Observable<Observable<Integer>>` and you need to flatten this before subscribing or the inner Observable won't get subscribed to.

```java
    @Test
    public void testUpdateParameterListOperatorWithError() {
        Database db = DatabaseCreator.db();
        TestSubscriber<Integer> ts = TestSubscriber.create();
        RuntimeException ex = new RuntimeException();
        Observable.<Observable<Object>> error(ex)
                // update
                .lift(db.update("update person set name=?||'zz' where name = ?")
                        .parameterListOperator())
                // flatten
                .flatMap(o -> o)
                .subscribe(ts);
        ts.assertError(ex);
    }
```

**Comment by Crystark** [comment]
Looking to my first example I think you're right and I was forgetting to flatten the observable probably because it was kind of a final action and i didn't care about the update's results.

Thanks for your help. I'll close that issue :)
