### ISSUE TITLE
Create doOnNext()-like Operator that provides access to SQL?

### ISSUE THREAD

**Issue by thomasnield** [davidmoten/rxjava-jdbc#47]
Hi David,

Maybe there's a feature in the logging framework I'm not using, but it would be helpful if somehow I could get the parameterized SQL String emitted on a ```doOnNext()``` fashion every time a query is executed. 
```
myDb.select("SELECT * FROM MY_TABLE WHERE EFF_TO = ?")
    .parameters(effToDates)
    .sqlOnNext(sql -> System.out.println(sql))
    .get(rs -> new MyItem(rs));
```

Would this be hard to add to the ```QuerySelect.Builder``` class? I've been poking around trying to find a place to put it for a PR, but to no avail yet.

**Comment by davidmoten** [comment]
DEBUG logging currently prints out the select sql statements called but not the parameters. update/insert/delete statements are printed out with their sql parameters. I'll ensure that select does as well. 

By the way at no stage do I build the sql string with parameter values inserted. That is done by the jdbc driver. I'm not aware of a standard way of eliciting more logging from jdbc drivers. I think they are all different in that regard but certainly some do support logging when instructed to.

**Comment by thomasnield** [comment]
Okay thank you, I was afraid the PreparedStatement didn't provide access to the parameterized SQL. I'll see of  can get the log to work for me now. Thank you.

**Comment by thomasnield** [comment]
I don't mean to sound like a newbie but I've got the logging libraries imported. How do I enable debug globally?
