### ISSUE TITLE
Query with "... like ''%?%" gets empty parameters

### ISSUE THREAD

**Issue by bzz** [davidmoten/rxjava-jdbc#48]
On the 0.6.9-SNAPSHOT as of latest master c09bad374d0f62ce5ddb5bd433527a6bb71416b0 (w/ #47 fixed) I get empty paramagnets for queries containing `like '%?%'` 

In a query 
```java
db
  .select("SELECT * FROM table_name WHERE column_name like '%?%'")
  .parameter(value)
  ...
```

the debug output looks like this

```
QuerySelectOnSubscribe:106 - preparing statement,sql=SELECT * FROM table_name WHERE column_name like '%?%'
QuerySelectOnSubscribe:125 - executing sql=SELECT * FROM table_name WHERE column_name like '%?%', parameters []
```

This query works as fine and actual parameters logged well 
```sql
SELECT * FROM table_name WHERE column_name like ?
```

This one does not work again
```sql
SELECT * FROM viewer_urls WHERE lower(showcases) like '?'
```

Could you please point if I'm doing something wrong here?

**Comment by bzz** [comment]
Well, I guess there should be another way to make `like '%?%'` query that I'm missing.

[UtilTest.java#L443](https://github.com/davidmoten/rxjava-jdbc/blob/master/src/test/java/com/github/davidmoten/rx/jdbc/UtilTest.java#L443) explains why I see empty parameter list in debug output

```java
Util.countQuestionMarkParameters("select name from blah where a < '?' and b = ?") == 1
```

**Comment by bzz** [comment]
Apparently this is an expected behaviour and problem was in expectations on how JDBC handles parameters.

The right way to do would be

```java
db
  .select("SELECT * FROM table_name WHERE column_name like ?")
  .parameter("%" + value + "%s")
  ....
```

**Comment by davidmoten** [comment]
Yep I agree with your finding, and you're welcome!
