### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by wsalembi** [davidmoten/rxjava-jdbc#55]
I think something's wrong with the exception handling. This code does not generate any errors, it returns an empty Observable. `doOnError` is never called.

        db.select("select name, score from person order by name")
                .getAs(Person.class)  // mistakenly replaced autoMap by getAs
                .doOnError(Throwable::printStackTrace)
                .forEach(System.out::println);

In reality a ClassCastException occurs (String.class cannot be cast to Person.class), but this programming is completely hidden to the developer. This makes using and debugging this library very hard.

**Comment by thomasnield** [comment]
I have found putting a doOnError() operator will give me access to an error, e.g. printing its stack trace. I have noticed this too though. Don't know if I'm using it wrong...

**Comment by davidmoten** [comment]
Thank you for the report, I'll have a look soon.

**Comment by davidmoten** [comment]
Sorry for the delay.

You're right. In this case the developer should see an `OnErrorNotImplementedException` so I've fixed that.

**Comment by davidmoten** [comment]
Fix released to Maven Central rxjava-jdbc 0.7.1. Thanks for the report!
