### ISSUE TITLE
Subscribe seems to be blocking

### ISSUE THREAD

**Issue by ldaria** [davidmoten/rxjava-jdbc#58]
Hello,
I'm facing an issue when subscribing to returned Observable from rxjava-jdbc. When I'm subscribing to the Observable stream it seems that subscribe() method is blocking.
See the following code:

```java
Observable<String> score = db.select("select name from users").getAs(String.class);
score.subscribe(System.out::println, Throwable::printStackTrace, () -> System.out.println("onCompleted"));
System.out.println("after subscribe");
```

I'm just doing a basic select query and after the subscribe I'm printing some message. But for some reason the message appears only after the query executes and "onCompleted" is printed.

I don't call .toBlocking() as in all your examples. However, I see that the subscribe() call is blocking.
I've checked this functionality with both mySQL driver ("com.mysql.jdbc.Driver") and Hive driver ( "org.apache.hive.jdbc.HiveDriver" ) and I see the same behavior - the subscribe() call is blocking.

Am I doing something wrong?
Thanks!

**Comment by thomasnield** [comment]
By default it schedules on the current thread. You need to use subscribeOn() to put it on a different thread other than the main one.

**Comment by davidmoten** [comment]
Seems like it's been answered (thanks @thomasnield !) so I'm closing
