### ISSUE TITLE
Implement Iterator<ResultSet>

### ISSUE THREAD

**Issue by thomasnield** [davidmoten/rxjava-jdbc#59]
Hey David!

My team and I have become so happy with this library and its features, we occasionally want to use it in a non-reactive capacity. It would be helpful if the `QuerySelect.Builder` had a method to return an `Iterator<ResultSet>` and not just an `Observable<ResultSet>`. I might have researched and developed a way you can turn an `Observable<ResultSet>` into a Java 8 `Stream<ResultSet>` or Kotlin `Sequence<ResultSet>` easily without major disruption to this library's underlying architecture.

Of course, you can call `toBlocking()` and get an `Iterator` but it does some buffering which is unsafe for a stateful `ResultSet`. Fortunately I think I did the hard work and I'll test it some more. The first thing needed is a specialized synchronizer which I researched on SO and adapted for this purpose.

```java
public final class SingleBlockingQueue<T> {
    private volatile T value;
    private final Semaphore full = new Semaphore(0);
    private final Semaphore empty = new Semaphore(1);
    private volatile boolean isDone = false;

    private volatile boolean hasValue = false;

    public void offer(T value) throws InterruptedException {
        empty.acquire();
        this.value = value;
        hasValue = true;
        full.release();
    }

    public T take() throws InterruptedException {
        full.acquire();
        T returnValue = value;
        value = null; // Should release reference
        hasValue = false;
        empty.release();
        return returnValue;
    }
    public void setDone() {
        isDone = true;
    }
    public boolean isDone() {
        return isDone;
    }
    public boolean hasValue() {
        return hasValue || !isDone;
    }
}
```

And then you need an `ObservableIterator` that uses this synchronizer to safely relay the `ResultSet` from the `Observable` to the `Iterator`. Sorry I wrote it in Kotlin, I can rewrite it in Java if needed.

```kotlin
class ObservableIterator<T>(
        observable: Observable<T>
) : Iterator<T>, Closeable {

    private val queue = SingleBlockingQueue<T>()

    private val subscription =
            observable
                    .subscribeWith {
                        onNext { queue.offer(it) }
                        onCompleted { queue.setDone() }
                        onError { queue.setDone() }
                    }

    override fun hasNext(): Boolean {
        return queue.hasValue()
    }

    override fun next(): T {
        return queue.take()
    }
    override fun close() {
        subscription.unsubscribe()
        queue.setDone()
    }
}
```

This will allow the use of RxJava-JDBC in a functional, serialized, but non-reactive way without having to collect and cache data. What do you think?

**Comment by thomasnield** [comment]
I think I overlooked something. The semaphores are not set up correctly. The `offer()` needs to block until it receives instruction to send next `ResultSet`.

**Comment by thomasnield** [comment]
Alright, this implementation seems to work great with the `ResultSet`.

```java
public final class SingleBlockingQueue<T> {
    private volatile T value;
    private final Semaphore nextGate = new Semaphore(0);
    private final Semaphore waitGate = new Semaphore(0);

    private volatile boolean hasValue = true;
    private volatile boolean isFirst = true;

    public void offer(T value) throws InterruptedException {
        if (isFirst) {
            nextGate.acquire();
            isFirst = false;
        }
        this.value = value;
        waitGate.release();
        nextGate.acquire();
    }

    public T take() throws InterruptedException {
        T returnValue = value;
        value = null; // Should release reference
        return returnValue;
    }
    public boolean next() throws InterruptedException {
        nextGate.release();
        waitGate.acquire();
        return hasValue;
    }
    public void setDone() {
        hasValue = false;
        waitGate.release();
    }
}
```

And the Kotlin usage to turn an `Observable<T>` into a `Sequence<T>`, and safetly works with `ResultSet` for `T`. 

```kotlin
import com.github.davidmoten.rx.jdbc.QuerySelect
import rx.Observable
import rx.Scheduler
import rx.lang.kotlin.subscribeWith
import java.io.Closeable

class ObservableIterator<T>(
        observable: Observable<T>
) : Iterator<T>, Closeable {

    private val queue = SingleBlockingQueue<T>()

    private val subscription =
            observable
                    .subscribeWith {
                        onNext { queue.offer(it) }
                        onCompleted { queue.setDone() }
                        onError { queue.setDone() }
                    }

    override fun hasNext(): Boolean {
        return queue.next()
    }

    override fun next(): T {
        return queue.take()
    }
    override fun close() {
        subscription.unsubscribe()
        queue.setDone()
    }
}

fun <T> Observable<T>.asSequence() = ObservableIterator(this).asSequence()

fun QuerySelect.Builder.asSequence(scheduler: Scheduler) = get { it }
        .subscribeOn(scheduler)
        .asSequence()
```

**Comment by davidmoten** [comment]
Interesting Thomas, I can see a few things to address but I'll start with a
biggie. This won't work with Schedulers.immediate() will it? Looks like it
will lock up.

**Comment by thomasnield** [comment]
That is correct. The Observable<ResultSet> must be subscribed on any other thread but the immediate one. But the Iterator<ResultSet> will run on the immediate thread, likely in a Java 8 Stream or Kotlin Sequence.

**Comment by thomasnield** [comment]
My only concern so far is this requires a heavy amount of synchronization and blocking. The offering and taking threads will alternate locks back and forth to each other to safely pass the ResultSet without altering it's state. The performance may suffer a little as a result, but it might be a worthwhile compromise to gain the functionality.

**Comment by thomasnield** [comment]
I suppose another way the API can be set up is do something similar to the get() call and specify a Func1<ResultSet,T>. That would require less synchronization since the ResultSet isn't passed to the Iterator, but rather the mapped item T.

Actually, I would overload getAsIterator()  with an optional Func1<ResultSet,T> argument which would use a different synchronizer. 

Anyway, it's late here. Look forward to hearing any ideas you may have later.

**Comment by davidmoten** [comment]
>I suppose another way the API can be set up is do something similar to the get() call and specify a Func1. That would require less synchronization since the ResultSet isn't passed to the Iterator, but rather the mapped item T.

That is the preferred option in Observable land too. You really want to map to another object as early as possible before downstream moves the `ResultSet` to another thread. In general I would not rely on all JDBC implementations of `ResultSet` being thread-safe or even designed for use outside of a single thread.

**Comment by thomasnield** [comment]
Yeah if that is the case, I actually I am starting to realize you could just call toBlocking() and get the iterator, so maybe this proposal is not even necessary...

**Comment by thomasnield** [comment]
Okay, on that note I think that the existing functionality in RxJava's `toBlocking().getIterator()` might be more than sufficient and a better solution. The `BlockingOperatorToIterator` backing it uses a non-capacity `LinkedBlockingQueue<T>` which probably allows more throughput. 

It also works on or off the `immediate()` Scheduler, although being on another `Scheduler` will allow the emissions to interleave nicely.

```kotlin
    Observable.range(1,100)
        .doOnNext { Thread.sleep(10) } //slow down emissions a little
        .subscribeOn(Schedulers.io())
        .doOnNext { println(it) }.toBlocking()
        .iterator
        .asSequence()
        .forEach { println("Sequence: $it") }
```

**OUTPUT:**

```
1
Sequence: 1
2
Sequence: 2
3
Sequence: 3
4
Sequence: 4
5
Sequence: 5
6
Sequence: 6
7
Sequence: 7
8
... //and so on!
````

So I can close this if needed, and sorry for taking up the time when a solution already existed.

**Comment by davidmoten** [comment]
All good then, it was interesting to follow.

**Comment by thomasnield** [comment]
Indeed it was.
