### ISSUE TITLE
FetchSize cannot be set to Integer.MIN_VALUE

### ISSUE THREAD

**Issue by litalk** [davidmoten/rxjava-jdbc#78]
JDBC streaming queries can only be performed if FetchSize=Integer.MIN_VALUE.

https://stackoverflow.com/questions/20899977/what-and-when-should-i-specify-setfetchsize
https://dev.mysql.com/doc/connector-j/5.1/en/connector-j-reference-implementation-notes.html

This makes the library unusable for me :(

**Comment by michele-mancioppi** [comment]
I'll send in a PR for that :-)

**Comment by michele-mancioppi** [comment]
We need to relax (remove?) the validation here: https://github.com/davidmoten/rxjava-jdbc/blob/4de9cc94b322d8a7d81b43528a1f55c2947fa691/src/main/java/com/github/davidmoten/rx/jdbc/QuerySelectOnSubscribe.java
