### ISSUE TITLE
Help: problem with Oracle Connection when I want to run a query

### ISSUE THREAD

**Issue by marianogambino** [davidmoten/rxjava-jdbc#94]
Hello,

I am doing a test with rxjava-jdbc with a  Oracle connection to know the behavior and how it works with parallel queries
When I run the test I get the following error when the ResultSet asks if the connection is closed

Code:

        Database db = 
        Database.from("jdbc:oracle:thin:@xx.xx.xx.xxx:1521:SOMETHING", "xxxxx", "xxxxx");
        Observable<List<String>> description = db
                .select(" select description   \n" +
                        " from description  \n" +
                        " where a  = ? and b  = ? ")

                .parameter("1234")
                .parameter("1234")
                .getAs(String.class)
                .toList();

        description .subscribe( s-> {
            System.out.print( s.toString() );
        });
    }

Error:

 java.lang.AbstractMethodError: Method oracle/jdbc/driver/OracleResultSetImpl.isClosed()Z is abstract

Maven POM.xml

        <dependency>
            <groupId>com.oracle</groupId>
            <artifactId>ojdbc7</artifactId>
            <version>12.1.0.2</version>
        </dependency>

        <dependency>
            <groupId>com.github.davidmoten</groupId>
            <artifactId>rxjava-jdbc</artifactId>
            <version>0.7.16</version>
        </dependency>

In addition, I have tried other versions of OJDBC but I get the same error.

Someone has any idea ?

Thanks a lot

**Comment by sparty02** [comment]
Which version of the JVM are you running this on?

**Comment by marianogambino** [comment]
JDK 1.8

**Comment by davidmoten** [comment]
I compile at 1.8 and run on 1.8, use oracle driver 12.2.0.1 and rxjava-jdbc 0.7.15 and no problems.

**Comment by davidmoten** [comment]
Can you try with 0.7.15? Perhaps I built the last release with the wrong JDK.

**Comment by marianogambino** [comment]
Hello David,
I tried with 

    
       
            <dependency>
                   <groupId>com.oracle</groupId>
                   <artifactId>ojdbc8</artifactId>
                   <version>12.2.0.1</version>
            </dependency>

            <dependency>
                 <groupId>com.github.davidmoten</groupId>
                 <artifactId>rxjava-jdbc</artifactId>
                 <version>0.7.15</version>
             </dependency>

and I get the same error.

**Comment by marianogambino** [comment]
Hi all,
It's working fine.

I had a library conflict between modules in Intellij. One of the modules had a version of ojdbc5 in which the implementation does not have the isClosed method.

I updated the dependency and the problem was solved.

Thanks for the help.
